# Generated by Django 4.1.5 on 2023-01-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(blank=True, max_length=85, null=True)),
                ('mentor', models.CharField(blank=True, max_length=85, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='room',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='standerd',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], default='', max_length=55),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='student',
            name='stack',
            field=models.CharField(choices=[('Python', 'PYTHON'), ('Java', 'JAVA')], default='', max_length=55),
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='app.student'),
        ),
    ]
