# Generated by Django 4.1.5 on 2023-01-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_classroom_delete_room_delete_subject_delete_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=55),
        ),
    ]
