# Generated by Django 4.1.5 on 2023-01-28 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_classroom_joined_on_student_joined_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='joined_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
