# Generated by Django 4.1.5 on 2023-01-28 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_classroom_joined_on_alter_student_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
